### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by casper** [lostdusty/cobalt#2]
I get the above error running cobalt on most instances.
Is the current release incompatible or how can I get it to work?
Thank you.

**Comment by lostdusty** [comment]
It was a bug on the gobalt library, just fixed it. I'll release a new version of cobalt-cli tomorrow (at my timezone)

**Comment by casper** [comment]
Awesome. Thank you! :)

**Comment by jasursadikov** [comment]
Hi, I also experience this issue
![image](https://github.com/user-attachments/assets/d2375efa-f5e7-470f-b50f-55166596ed79)

**Comment by lostdusty** [comment]
Also, this issue happens because cobalt.tools doesnt offer a free api anymore, while I fix this, you guys can change the instance used. Use `cobalt instances` to see other instances, and use the flag `-i` to change the instance used. Remeber to use a instance running version 7.x

**Comment by casper** [comment]
The documentation on the API is very confusing. On one hand it says there is no API, on the other hand they tell us if we wish to use the latest API, all we need is to read the documentation. 

> Currently, there is no publicly accessible main api. we plan on providing a public api for cobalt 10 in some form in the future. we recommend deploying your own instance **if you wish to use the latest api**. you can access [the documentation](https://github.com/imputnet/cobalt/blob/main/docs/api.md) for it here.

If I look at the docs, it seems like the root URL has changed from /api/json to just /. 
Have you tried if that would work?

**Comment by lostdusty** [comment]
Yes, I've changed it on the library with the new api version 10 (https://github.com/lostdusty/gobalt/commit/b9c106c0d3d8ca1985d9fbc95784a95c087003ed), but this only supports servers running cobalt version 7.15 and below. There is no public api from cobalt anymore, but rather from the community

**Comment by lostdusty** [comment]
Should work now (https://github.com/lostdusty/cobalt/commit/4cadf7c79f40f197753e18490ecbe39523d4becb), please tell me if you find any more issues.

**Comment by KwiatekMiki** [comment]
> On one hand it says there is no API, on the other hand they tell us if we wish to use the latest API, all we need is to read the documentation.

> we recommend deploying your own instance if you wish to use the latest api

i can easily understand that they're trying to say something like: host your own instance if you want to use the latest api but if you don't want to host your own instance then use the old api

i don't recommend using the old api since it'll get removed soon<sup><a href="https://discord.com/channels/1049706293700591677/1049706293700591680/1294738221594574930">[1]</a></sup>

also, the documentation has improved now and it doesn't say that anymore so it's less confusing now<sup><a href="https://github.com/imputnet/cobalt/commits/main/docs/api.md?since=2024-10-12&until=2024-10-12">[2]</a></sup>
