### ISSUE TITLE
cobalt rejected our request: error.api.auth.jwt.missing

### ISSUE THREAD

**Issue by DylwinTFTW** [lostdusty/cobalt#3]
OS: Windows 10

I'm trying to download things with this tool, and whenever I do I get this output.

INFO[2024-10-22T03:01:43-04:00] Sending request to cobalt server...
FATA[2024-10-22T03:01:43-04:00] cobalt rejected our request: error.api.auth.jwt.missing

I installed the app by downloading the executable and putting the folder it's in in path, is there anything else I should be doing?

**Comment by lostdusty** [comment]
Someone abused all cobalt instances, not much what we can do, other than selfhosting a cobalt instance
